name: molgrid
channels:
  - conda-forge
  - nodefaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attr=2.5.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cpython=3.10.19
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.9.79
  - cuda-nvcc-tools=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-tools=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - filelock=3.20.0
  - fmt=12.0.0
  - fsspec=2025.12.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - jinja2=3.1.6
  - ld_impl_linux-64=2.45
  - libabseil=20250512.1
  - libblas=3.11.0
  - libcap=2.77
  - libcblas=3.11.0
  - libcublas=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcudss=0.7.1.4
  - libcufft=11.4.1.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmagma=2.9.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libnvjitlink=12.9.86
  - libprotobuf=6.31.1
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libtorch=2.9.1
  - libudev1=258.3
  - libuuid=2.41.2
  - libuv=1.51.0
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - markupsafe=3.0.3
  - mkl=2025.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nccl=2.28.9.1
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=2.2.6
  - openssl=3.6.0
  - optree=0.18.0
  - pip=25.3
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - python=3.10.19
  - python_abi=3.10
  - pytorch=2.9.1
  - rdma-core=60.0
  - readline=8.3
  - setuptools=80.9.0
  - sleef=3.9.0
  - sympy=1.14.0
  - tbb=2022.3.0
  - tk=8.6.13
  - triton=3.5.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wheel=0.45.1
  - zstd=1.5.7
prefix: /home/yoonseu5/anaconda3/envs/molgrid
